project:
  type: website

filters:
  - convert-to-webp
webp-delete-originals: false
webp-disable: false

website:
  title: "Norman's Academic Blog"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Veröffentlichungen"
        href: publications.qmd
    right:
      - icon: rss
        href: blog.xml
  site-url: https://www.sefiroth.de
  description: "Norman's Academic Blog"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



