project:
  type: website
filters:
  - convert-to-webp
website:
  title: "Norman's Academic Blog"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Veröffentlichungen"
        href: publications.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



