---
title: "Wie mensch eine Datenbank auf einem RASPBERRY Pi Zero installiert"
author: "Norman Markgraf"
lang: de-DE
date: "2025-08-09"
date-modified: last-modified
word-count: true
reading-time: true
categories: 
  - RaspberryPi
  - Datenbank
---


## Einrichten des Raspberry Zero

### Schrit 1: Neues Betriebssystem installieren 

Am besten mit dem Raspberry Pi Installer
von hier: <https://www.raspberrypi.com/software/>

Für einen Raspberry Zero: *Raspberry Pi OS (32-bit) Lite*

Für einen Raspberry Zero 2 W: *Raspberry Pi OS (64-bit) Lite*

**Wichtig** MIT SSH konfigurieren!


### Schrit 2: Ein Link zum Display

Auf dem RaspberryPI Zero ist ein Waveshare 2-13inch-e-Paper HAT installiert. Alles Wichtige dazu findet sich unter:
<https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_Manual#Working_With_Raspberry_Pi>

Damit das Display richtig funktioniert sollte man in der `config.txt` die folgende Zeile anpassen:

```
dtparam=spi=on
```

### Schritt 3: Den Raspberry Pi im Netz suchen und finden

Es gibt viele Weg die zum Ziel führen (können).

Zum Beispiel mit dem Befehl `nmap`:

```bash
> nmap -sn 192.168.2.0/24
```

Oder einfach den Hostnamen "raspberrpi.local" nutzen.

Man kann sich somit ggf. mittels ssh und dem folgenden Kommando anmelden:

```bash
> ssh norman@raspberrypi.local
```

Ebenso kann [R PI Connect](http://connect.raspberrypi.com)  benutzt werden, wenn man es vorher eingerichtet hat.


### Schritt 4: Startup-Display installieren

Ich habe bei GitHub ein kleines Programm geschrieben, welches die aktuelle IP Address (IP4 und IP6 sowie die aktuelle Uhrzeit) auf dem Display ausgibt.

Es ist unter <https://github.com/NMarkgraf/pi-startup-display> zu finden und wird einfach in das Hauptverzeichnis des Nutzers "norman" unter "/home/norman" per

```bash
> git clone https://github.com/NMarkgraf/pi-startup-display 
```

installiert.

Später kann dann im Verzeichnis `pi-startup-display` einfach das aktuelle Release von GutHUb durch den folgenden Befehl geladen werden:

```bash
> git pull
```

Damit dieses Skript nach jedem Neustart automatisch (einmal) gestartet wird bin ich nach dem Beispiel von <https://webnist.de/automatisches-starten-eines-python-skripts-auf-dem-raspberry-pi-mit-systemd/> vorgegangen.

Aber ich habe die service Datei "/etc/systemd/system/startup-display.service" wie folgt angepasst:

```
[Unit]
Description=startup-display
After=network.target
 
[Service]
ExecStart=/usr/bin/python3 -u /home/norman/pi-startup-display/start-display.py 
WorkingDirectory=/home/norman/pi-startup-display/
#StandardOutput=inherit
StandardOutput=file:/tmp/start-display.log
#StandardError=inherit
StandardError=file:/tmp/start-display-error.log
#Restart=always
Restart=on-failture
RestartSec=60
User=norman
 
[Install]
WantedBy=multi-user.target
```
Zum anlegen habe ich den Editor "nano" genutzt und die Datei gleich mit angelegt.

```bash
> sudo nano /etc/systemd/system/startup-display.service
```

Die geänderte Datei muss nun initialisiert werden mit:

```bash
> sudo systemctl daemon-reload
> sudo systemctl enable startup-display.service
```

Dann können wir alles, zum Testen, von Hand starten:

```bash
> sudo systemctl start startup-display.service
```

Ob alles zu unserer Zufriedenheit funktioniert können wir mit der Status-Anzeige mit dem folgenden Befehl prüfen:

```bash
> sudo systemctl status startup-display.service
```

Und natürlich ggf. auch stoppen:

```bash
> sudo systemctl stop startup-display.service
```


## PostgreSQL installieren

Ich gehe wie folgt vor:

### Schritt 1: Installieren von PostgreSQL 

Da es ein deb Paket gibt, nehme ich den leichten Weg:

```bash
> sudo apt install postgresql
```

### Schritt 2:  Wechseln auf Nutzer:in "postgres"

Wir kommunizieren mit PostgreSQL durch den Benutzer "postgres", in den wir uns verwandelt:

```bash
> sudo su postgres
```

### Schritt 3: Herunterladen der Demo-Daten, entpacken und installieren

Die erste Demo-Daten erhalten wir durch:

```bash
> curl -L -O https://github.com/lerocha/netflixdb/releases/download/v1.0.16/netflixdb-postgres.zip
> unzip netflixdb-postgres.zip
```

Da Daten können wir dann in die Datenbank "netfix" einfügren:

```bash
> sudo su postgres
> psql -d netflix
> \i /home/norman/netflixdb-postgres.sql
```

Jetzt ist die Datenbank "netflix" in PostgreSQL installiert.

Und wir können diese nun mit den folgenden Parametern ansprechen:

```
  ip:       ???? 
  port:     5342
  user:     postgres
  password: postgresdemo 
  dbname:   netflix
```

### Schritt 4: AdminerNEO installieren 

AdminerNEO ist ein Webtool für die Verwaltung von PostgreSQL.

Wir installieren die aktuelle Version von der Website:
<https://www.adminneo.org/download>
