<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de-DE" xml:lang="de-DE"><head>

<meta charset="utf-8">
<<<<<<< HEAD
<meta name="generator" content="quarto-1.8.26">
=======
<meta name="generator" content="quarto-1.8.25">
>>>>>>> 5520f36 (Merge)

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Norman Markgraf">

<title>Über die Koeffizienten einer linearen Regression – Norman’s Academic Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<<<<<<< HEAD
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
=======
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
>>>>>>> 5520f36 (Merge)
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f245066ca199b7326ac6b360085ddf3a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Norman’s Academic Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Suchen"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navigation umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Veröffentlichungen</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projekte.html"> 
<span class="menu-text">Projekte</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../blog.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Über die Koeffizienten einer linearen Regression</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Statistik</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor:in</div>
      <div class="quarto-title-meta-contents">
               <p>Norman Markgraf </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Veröffentlichungsdatum</div>
      <div class="quarto-title-meta-contents">
        <p class="date">9. Juni 2021</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Geändert</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">3. Dezember 2025</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>Bei einer <em>einfachen Regression</em> versuchen wir zu gegebenen Datenpunkten <span class="math inline">\((x_1, y_1), ..., (x_n, y_n)\)</span> eine <em>möglichst passende</em> Funktion <span class="math inline">\(g(x)\)</span> zu finden, so dass <span class="math display">\[y_i = g(x_i) + e_i\]</span> gilt. Dabei tolerieren wir eine (kleine) Abweichung <span class="math inline">\(e_i\)</span>.</p>
<p>Bei einer <em>einfachen <strong>linearen</strong> Regression</em> gehen wir davon aus, dass die Datenpunkte (im wesentlichen) auf einer Geraden liegen. Mit <span class="math inline">\(g(x)=\beta_0 + \beta1 \cdot x\)</span> ergibt sich dann für die Datenpunkte die Gleichung:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 \cdot x_i + e_i\]</span></p>
<p>Unsere Aufgabe besteht nun darin die Parameter <span class="math inline">\(\beta_0\)</span> (y-Achsenabschnitt) und <span class="math inline">\(\beta_1\)</span> (Steigung) an Hand der <span class="math inline">\(n\)</span> Datenpunkte zu schätzen. Alle unsere Schätzungen kennzeichnen wir mit einem Dach (<span class="math inline">\(\hat{.}\)</span>), um sie von den (in der Regel unbekannten) Parametern besser zu unterscheiden.</p>
<p>Wir suchen somit nach <span class="math inline">\(\hat\beta= \left(\hat\beta_0,\, \hat\beta_1\right)\)</span>, so dass die Gerade <span class="math inline">\(\hat\beta_0 + \hat\beta_1 \cdot x\)</span> zu gegebenem <span class="math inline">\(x_i\)</span> eine möglichst gute Schätzung von <span class="math inline">\(y_i\)</span> (genannt <span class="math inline">\(\hat{y}_i\)</span>) hat:</p>
<p><span class="math display">\[
\hat{y_i} = \hat\beta_0 + \hat\beta_1 \cdot x_i
\]</span></p>
<p>Die Abweichung <span class="math inline">\(\hat{e_i}\)</span> unserer Schätzung <span class="math inline">\(\hat{y}_i\)</span> von dem gegebenen Wert <span class="math inline">\(y_i\)</span> lässt sich schreiben als:</p>
<p><span class="math display">\[
\hat{e_i} =  \hat{y_i} - y_i =  \hat\beta_0 + \hat\beta_1 \cdot x_i - y_i
\]</span></p>
<p>Wenn wir diese Abweichung über alle <span class="math inline">\(i\)</span> minimieren, finden wir unser <span class="math inline">\(\hat\beta\)</span>.</p>
<p>Doch das wirft eine Frage auf: <em>Wie genau messen wir die möglichst <strong>kleinste Abweichung</strong> der</em> <span class="math inline">\(\hat{e_i}\)</span> konkret?</p>
<p>Wir betrachten zunächst drei einfache Ideen:</p>
<ol type="1">
<li><p>Idee: <em>Betrag der Summe der Abweichungen</em></p></li>
<li><p>Idee: <em>Summe der absoluten Abweichungen</em></p></li>
<li><p>Idee: <em>Summe der quadratischen Abweichungen</em></p></li>
</ol>
<p>Gewöhnlich nutzen wir die <em>quadratischen Abweichungen</em>, weshalb wir die drei Ideen ebenso in umgekehrter Reihenfolge betrachten wollen:</p>
<section id="idee-summe-der-quadratischen-abweichungen" class="level2">
<h2 class="anchored" data-anchor-id="idee-summe-der-quadratischen-abweichungen">3. Idee: Summe der quadratischen Abweichungen</h2>
<p>Wir bezeichnen mit</p>
<p><span class="math display">\[\begin{aligned}
QS &amp;= QS(\hat\beta) = QS(\hat\beta_0, \hat\beta_1) \\
  &amp;= \sum\limits_{i=1}^n \hat{e_i}^2 = \sum\limits_{i=1}^n \left(\hat{y_i} - y_i \right)^2 \\
  &amp;= \sum\limits_{i=1}^n \left(\hat\beta_0 + \hat\beta_1 \cdot x_i - y_i \right)^2
\end{aligned}\]</span></p>
<p>die <strong>Q</strong>uadrat-<strong>S</strong>umme der Abweichungen.</p>
<p>Gesucht wird <span class="math inline">\(\hat\beta=\left(\hat\beta_0,\,\hat\beta_1\right)\)</span>, so das <span class="math inline">\(QS\)</span> minimiert wird.</p>
<p>Dies ist ein Minimierungsproblem, bei dem wir zu mindestens eine (exakte) mathematisch-algebraisch Lösung in Form eines stationären Punktes finden können. Dazu berechnen wir die Nullstelle der ersten partiellen Ableitung von <span class="math inline">\(QS\)</span> nach <span class="math inline">\(\hat\beta_0\)</span> bzw. <span class="math inline">\(\hat\beta_1\)</span>.</p>
<section id="vorbemerkungen" class="level3">
<h3 class="anchored" data-anchor-id="vorbemerkungen">Vorbemerkungen</h3>
<p>Wegen <span class="math inline">\(\bar{x} = \frac{1}{n} \sum\limits_{i=1}^n x_i\)</span> ist <span class="math inline">\(n \cdot \bar{x} =\sum\limits_{i=1}^n x_i\)</span> und analog <span class="math inline">\(n \cdot \bar{y} =\sum\limits_{i=1}^n y_i\)</span></p>
</section>
<section id="schätzen-des-y-achenabschnitts-hatbeta_0" class="level3">
<h3 class="anchored" data-anchor-id="schätzen-des-y-achenabschnitts-hatbeta_0">Schätzen des y-Achenabschnitts <span class="math inline">\(\hat\beta_0\)</span></h3>
<p>Es ist:</p>
<p><span class="math display">\[\begin{aligned}
\frac{\partial}{\partial \hat\beta_0} \, QS &amp;= 2 \cdot \sum\limits_{i=1}^n \left(\hat\beta_0 + \hat\beta_1 \cdot x_i - y_i \right) \cdot 1 \\
  &amp;= 2 \cdot \left(\sum\limits_{i=1}^n \hat\beta_0 + \sum\limits_{i=1}^n\hat\beta_1 \cdot x_i - \sum\limits_{i=1}^n y_i\right) \\
  &amp;= 2 \cdot \left( n \cdot \hat\beta_0 + \hat\beta_1\cdot\sum\limits_{i=1}^n x_i - \sum\limits_{i=1}^n y_i \right) \\
  &amp;= 2 \cdot \left( n \cdot \hat\beta_0 + \hat\beta_1\cdot n \cdot \bar{x} - n \cdot\bar{y} \right) \\
  &amp;= 2 \cdot n \cdot \left( \hat\beta_0 + \hat\beta_1\cdot \bar{x} -\bar{y} \right)
\end{aligned}\]</span></p>
<p>Um stationäre Punkte zu ermitteln, müssen wir den Ausdruck nun gleich Null setzen und erhalten:</p>
<p><span class="math display">\[\begin{aligned}
  0 &amp;= \frac{\partial}{\partial \hat\beta_0} \, QS \\
  &amp;= 2 \cdot n \cdot \left( \hat\beta_0 + \hat\beta_1\cdot \bar{x} -\bar{y} \right) \qquad | : (2 \cdot n) \\
  &amp;= \hat\beta_0 + \hat\beta_1\cdot \bar{x} -\bar{y}
\end{aligned}\]</span></p>
<p>Stellen wir nach <span class="math inline">\(\hat\beta_0\)</span> um, erhalten wir:</p>
<p><span class="math display">\[\begin{aligned}
  \hat\beta_0 &amp;= - \hat\beta_1\cdot\bar{x} + \bar{y} \\
  \hat\beta_0 &amp;= \bar{y} - \hat\beta_1\cdot\bar{x}
\end{aligned}\]</span></p>
<p>Um <span class="math inline">\(\hat\beta_0\)</span> zu bestimmen, benötigen wir <span class="math inline">\(\hat\beta_1\)</span>.</p>
</section>
<section id="schätzen-der-steigung-hatbeta_1" class="level3">
<h3 class="anchored" data-anchor-id="schätzen-der-steigung-hatbeta_1">Schätzen der Steigung <span class="math inline">\(\hat\beta_1\)</span></h3>
<p>Es ist:</p>
<p><span class="math display">\[\begin{aligned}
  \frac{\partial}{\partial \hat\beta_1} \, QS &amp;= 2 \cdot \sum\limits_{i=1}^n \left(\hat\beta_0 + \hat\beta_1 \cdot x_i - y_i \right) \cdot x_i \\
  &amp;= 2 \cdot \left(\sum\limits_{i=1}^n \hat\beta_0 \cdot x_i + \sum\limits_{i=1}^n \hat\beta_1 \cdot x_i\cdot x_i- \sum\limits_{i=1}^n y_i \cdot x_i\right) \\
    &amp;= 2 \cdot \left(\hat\beta_0 \cdot \sum\limits_{i=1}^n  x_i + \hat\beta_1 \cdot\sum\limits_{i=1}^n x_i^2- \sum\limits_{i=1}^n y_i \cdot x_i\right) \\
    &amp;= 2 \cdot \left(\hat\beta_0 \cdot n \cdot \bar{x} + \hat\beta_1 \cdot\sum\limits_{i=1}^n x_i^2- \sum\limits_{i=1}^n y_i \cdot x_i\right)
\end{aligned}\]</span></p>
<p>Wir ersetzen nun <span class="math inline">\(\hat\beta_0\)</span> durch <span class="math inline">\(\bar{y} - \hat\beta_1\cdot \bar{x}\)</span> und erhalten:</p>
<p><span class="math display">\[\begin{aligned}
  \frac{\partial}{\partial \hat\beta_1} \, QS  &amp;=
  2 \cdot \left(\hat\beta_0 \cdot n \cdot \bar{x} + \hat\beta_1 \cdot\sum\limits_{i=1}^n x_i^2- \sum\limits_{i=1}^n y_i \cdot x_i\right) \\
  &amp;= 2 \cdot \left(\left(\bar{y} - \hat\beta_1\cdot \bar{x}\right) \cdot n \cdot \bar{x} + \hat\beta_1 \cdot\sum\limits_{i=1}^n  x_i^2- \sum\limits_{i=1}^n y_i \cdot x_i\right) \\
  &amp;= 2 \cdot \left(n \cdot\bar{y} \cdot \bar{x} - n \cdot \hat\beta_1 \cdot  \bar{x}^2  + \hat\beta_1 \cdot\sum\limits_{i=1}^n  x_i^2- \sum\limits_{i=1}^n y_i \cdot x_i\right) \\
  &amp;= 2 \cdot \left(n \cdot\bar{y} \cdot \bar{x} - \sum\limits_{i=1}^n y_i \cdot x_i  + \hat\beta_1 \cdot \left(\sum\limits_{i=1}^n  x_i^2- n \cdot  \bar{x}^2\right)\right) \\
\end{aligned}\]</span></p>
<p>Mit Hilfe des <a href="https://de.wikipedia.org/wiki/Verschiebungssatz_(Statistik)"><em>Verschiebesatzes von Steiner</em></a> (zweimal angewendet) erhalten wir:</p>
<p><span class="math display">\[\begin{aligned}
  \frac{\partial}{\partial \hat\beta_1} \, QS  
    &amp;=2 \cdot \left(n \cdot\bar{y} \cdot \bar{x} - \sum\limits_{i=1}^n y_i \cdot x_i  + \hat\beta_1 \cdot \left(\sum\limits_{i=1}^n  x_i^2- n \cdot  \bar{x}^2\right)\right) \\
    &amp;=2 \cdot \left(- \left(\sum\limits_{i=1}^n y_i \cdot x_i - n \cdot \bar{y} \cdot \bar{x}   \right)+ \hat\beta_1 \cdot \left(\sum\limits_{i=1}^n  x_i^2- n \cdot  \bar{x}^2\right)\right) \\
    &amp;=2 \cdot \left(\hat\beta_1 \cdot \left(\sum\limits_{i=1}^n  x_i^2- n \cdot  \bar{x}^2\right)- \left(\sum\limits_{i=1}^n y_i \cdot x_i - n \cdot \bar{y} \cdot \bar{x}   \right)\right) \\
    &amp;= 2 \cdot \left(\hat\beta_1 \cdot \sum\limits_{i=1}^n(x_i-\bar{x})^2 - \sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})\right)
\end{aligned}\]</span></p>
<p>Wir setzen nun wieder den Ausdruck gleich Null:</p>
<p><span class="math display">\[\begin{aligned}
0 &amp;= 2 \cdot \left(\hat\beta_1 \cdot \sum\limits_{i=1}^n(x_i-\bar{x})^2 - \sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})\right)  \qquad | : 2\\
   &amp;= \hat\beta_1 \cdot \sum\limits_{i=1}^n(x_i-\bar{x})^2 - \sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})
\end{aligned}\]</span></p>
<p>Und stellen dann nach <span class="math inline">\(\hat\beta_1\)</span> um:</p>
<p><span class="math display">\[\begin{aligned}
  \hat\beta_1 \cdot \sum\limits_{i=1}^n(x_i-\bar{x})^2
    &amp;= \sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y}) \\
  \hat\beta_1
    &amp;= \frac{\sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})}{\sum\limits_{i=1}^n(x_i-\bar{x})^2}
\end{aligned}\]</span></p>
<p>Wir können nun Zähler und Nenner der rechten Seite mit <span class="math inline">\(\frac{1}{n}\)</span> erweitern und erhalten so:</p>
<p><span class="math display">\[\begin{aligned}
\hat\beta_1
      &amp;= \frac{\frac{1}{n} \cdot\sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})}{\frac{1}{n} \cdot\sum\limits_{i=1}^n  (x_i-\bar{x})^2} \\
      &amp;= \frac{\sigma_{x,y}}{\sigma^2_x} \\
\end{aligned}\]</span></p>
<p>Oder aber wir erweitern mit <span class="math inline">\(\frac{1}{n-1}\)</span> und erhalten:</p>
<p><span class="math display">\[\begin{aligned}
\hat\beta_1
      &amp;= \frac{\frac{1}{n-1} \cdot\sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})}{\frac{1}{n-1} \cdot\sum\limits_{i=1}^n  (x_i-\bar{x})^2} \\
      &amp;= \frac{s_{x,y}}{s^2_{x}}
\end{aligned}\]</span></p>
<p>Damit können wir zur Berechnung sowohl die Kovarianz der Grundgesamtheit <span class="math inline">\(\sigma_{x,y}\)</span> und die Varianz <span class="math inline">\(\sigma^2_x\)</span> von <span class="math inline">\(x\)</span>, als auch deren Schätzer <span class="math inline">\(s_{x,y}\)</span> und <span class="math inline">\(s^2_x\)</span> verwendet werden!</p>
<p>Diese Methode nennt sich <strong>Methode der kleinsten Quadrate</strong> (engl. <em>ordenary least square method</em>) und wir sprechen dann auch von den <strong>Kleinste-Quadrate-Schätzern</strong> (oder kurz <strong>KQ-Schätzer</strong> bzw. <strong>OLS-Schätzer</strong>) <span class="math inline">\(\hat\beta_0\)</span> und <span class="math inline">\(\hat\beta_1\)</span>.</p>
<p>Erweitern wir den Ausdruck mit Standardabweichung <span class="math inline">\(\sigma_y\)</span> bzw. <span class="math inline">\(s_y\)</span>, so erhalten wir:</p>
<p><span class="math display">\[\begin{aligned}
\hat\beta_1 &amp;= \frac{\sigma_{x,y}}{\sigma^2_x} \cdot \frac{\sigma_y}{\sigma_y} = \frac{\sigma_{x,y}}{\sigma_x \cdot \sigma_x} \cdot \frac{\sigma_y}{\sigma_y} = \frac{\sigma_{x,y}}{\sigma_x \cdot \sigma_y} \cdot \frac{\sigma_y}{\sigma_x} \\
&amp;= \rho_{x,y} \cdot \frac{\sigma_y}{\sigma_x} \\
\end{aligned}\]</span></p>
<p>und analog für die Schätzer:</p>
<p><span class="math display">\[\begin{aligned}
\hat\beta_1 &amp;= \frac{s_{x,y}}{s^2_x} \cdot \frac{s_y}{s_y}
  = \frac{s_{x,y}}{s_x \cdot s_x} \cdot \frac{s_y}{s_y}
  = \frac{s_{x,y}}{s_x \cdot s_y} \cdot \frac{s_y}{s_x} \\
&amp;= r_{x,y} \cdot \frac{s_y}{s_x} \\
\end{aligned}\]</span></p>
<p>Die Steigung <span class="math inline">\(\hat\beta_1\)</span> hat somit eine direkte Beziehung mit dem <em>Korrelationskoeffizenten</em> <span class="math inline">\(\rho\)</span> (der Grundgesamtheit) bzw. <span class="math inline">\(r\)</span> (der Stichprobe).</p>
<p>Für eine Berechnung in <strong>R</strong> heißt dies: wir können die Regressionskoeffizienten <span class="math inline">\(\hat\beta_0\)</span> und <span class="math inline">\(\hat\beta_1\)</span> direkt algebraisch ausrechnen, wenn wir</p>
<ol type="a">
<li><p>die Standardabweichungen von <span class="math inline">\(x\)</span> und <span class="math inline">\(y\)</span> und den Korrelationskoeffizienten oder</p></li>
<li><p>die Varianz von <span class="math inline">\(x\)</span> und Kovarianz von <span class="math inline">\(x\)</span> und <span class="math inline">\(y\)</span></p></li>
</ol>
<p>haben.</p>
</section>
<section id="ein-beispiel-in-r" class="level3">
<h3 class="anchored" data-anchor-id="ein-beispiel-in-r">Ein Beispiel in R:</h3>
<p>Auf Grundlage der Datentabelle <em>mtcars</em> wollen wir Prüfen wie ein linearer Zusammenhang zwischen dem Verbrauch (in Meilen pro Gallone <em>mpg</em>) und der Leistung (Pferdestärke <em>hp</em>) modelliert werden kann.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Wir nehmen die Datentabelle 'mtcars':</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(hp, mpg) <span class="ot">-&gt;</span> dt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ein kurzer Blick auf die Daten:</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span> hp, <span class="at">data =</span> dt)[<span class="fu">c</span>(<span class="st">"mean"</span>,<span class="st">"sd"</span>)]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      mean       sd</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  146.6875 68.56287</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span> mpg, <span class="at">data =</span> dt)[<span class="fu">c</span>(<span class="st">"mean"</span>,<span class="st">"sd"</span>)]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      mean       sd</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  20.09062 6.026948</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Wir vergleichen den Verbrauch (mpg, miles per gallon) </span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># mit den Pferdestärken (hp) mit Hilfe eines Streudiagramms:</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> dt) <span class="sc">%&gt;%</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">35</span>))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Berechnen wir zunächst die Mittelwerte von <span class="math inline">\(x\)</span> (also ‘hp’) und <span class="math inline">\(y\)</span> (also ‘mpg’)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>(mean_hp <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="sc">~</span> hp, <span class="at">data =</span> dt))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 146.6875</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>(mean_mpg <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="sc">~</span> mpg, <span class="at">data =</span> dt))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 20.09062</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>und zeichnen die Punkt <span class="math inline">\((\bar{x}, \bar{y}) = (146.69, 20.09)\)</span> in unser Streudiagramm ein:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> dt) <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_hline</span>(<span class="at">yintercept =</span> <span class="sc">~</span> mean_mpg, <span class="at">color =</span> <span class="st">"grey60"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> <span class="sc">~</span> mean_hp, <span class="at">color =</span> <span class="st">"grey60"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(mean_mpg <span class="sc">~</span> mean_hp, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">35</span>))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Berechnen wir nun die Schätzwerte für die Regressionsgerade</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>(beta_1 <span class="ot">&lt;-</span> <span class="fu">cov</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> dt) <span class="sc">/</span> <span class="fu">var</span>(<span class="sc">~</span> hp, <span class="at">data =</span> dt))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.06822828</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>(beta_0 <span class="ot">&lt;-</span> mean_mpg <span class="sc">-</span> beta_1 <span class="sc">*</span> mean_hp)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 30.09886</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>und zeichnen diese in unser Streudiagramm ein:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> dt) <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_hline</span>(<span class="at">yintercept =</span> <span class="sc">~</span> mean_mpg, <span class="at">color =</span> <span class="st">"grey60"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> <span class="sc">~</span> mean_hp, <span class="at">color =</span> <span class="st">"grey60"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(mean_mpg <span class="sc">~</span> mean_hp, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_abline</span>(<span class="at">slope =</span> <span class="sc">~</span> beta_1, <span class="at">intercept =</span> <span class="sc">~</span>beta_0, <span class="at">color =</span> <span class="st">"dodgerblue"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">35</span>))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Die Funktionsvorschrift für die (blaue) Regressionsgerade lautet:</p>
<p><span class="math display">\[
\begin{aligned}
  \hat{y} &amp;= \hat\beta_0 + \hat\beta_1 \cdot x \\
          &amp;\approx 30.0988605 -0.0682283 \cdot x \\
          &amp;\approx 30.099 -0.068 \cdot x
\end{aligned}
\]</span></p>
</section>
<section id="studentisieren-einmal-hin-und-einmal-zurück" class="level3">
<h3 class="anchored" data-anchor-id="studentisieren-einmal-hin-und-einmal-zurück">Studentisieren – einmal hin und einmal zurück</h3>
<p>Was passiert eigentlich, wenn wir unsere <span class="math inline">\(x\)</span> und <span class="math inline">\(y\)</span> Werte studentisieren (aka standardisieren oder z-transformieren)?</p>
<p>Zur Erinnerung, studentisieren geht so: <span class="math display">\[
x^{stud} = \frac{x - \bar{x}}{s_x}
\]</span></p>
<p>In <strong>R</strong> können wir das mit der Funktion ‘zscore’ wie folgt machen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dt <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">hp_stud =</span> <span class="fu">zscore</span>(hp),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mpg_stud =</span> <span class="fu">zscore</span>(mpg)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> dt</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Natürlich sind die Mittelwerte nun Null und die Standardabweichungen Eins:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span> hp_stud, <span class="at">data =</span> dt)[<span class="fu">c</span>(<span class="st">"mean"</span>,<span class="st">"sd"</span>)]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           mean sd</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  -4.857226e-17  1</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span> mpg_stud, <span class="at">data =</span> dt)[<span class="fu">c</span>(<span class="st">"mean"</span>,<span class="st">"sd"</span>)]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          mean sd</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4.336809e-17  1</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Der Grund für die kleinen Abweichungen von der Null bei den Mittelwerten sind unumgängliche Rundungsfehler, die der Computer macht!</p>
<p>Schauen wir uns nun das Streudiagramm an, zusammen mit dem Mittelpunkt <span class="math inline">\((0,0)\)</span></p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(mpg_stud <span class="sc">~</span> hp_stud, <span class="at">data =</span> dt) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_point</span>(<span class="dv">0</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_lims</span>(<span class="at">y =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Auch wenn die Skalierungen sich geändert haben, die Diagramme sind sehr ähnlich.</p>
<p>Bestimmen wir die Koeffizienten der Regressionsgerade</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(beta_stud_1 <span class="ot">&lt;-</span> <span class="fu">cov</span>(mpg_stud <span class="sc">~</span> hp_stud, <span class="at">data =</span> dt))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.7761684</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>(beta_stud_0 <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="sc">-</span> beta_stud_1 <span class="sc">*</span> <span class="dv">0</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>und setzen sie in das Streudiagramm ein:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Wir können das studentisierte Problem auch wieder auf unser ursprüngliches zurück rechnen.</p>
<p>Die Regressionsgerade im studentisierten Problem lautet:</p>
<p><span class="math display">\[
\begin{aligned}
  \hat{y}^{stud} &amp;= \hat\beta^{stud}_0 + \hat\beta_1^{stud} \cdot x^{stud} \\
          &amp;\approx 0 -0.7761684 \cdot x^{stud} \\
          &amp;\approx 0 -0.776 \cdot x^{stud}
\end{aligned}
\]</span></p>
<p>Rechnen wir nun mittels der Formel <span class="math display">\[\hat\beta_1 = \hat\beta_1^{stud} \cdot \frac{s_y}{s_x}\]</span></p>
<p>die Steigung um, so erhalten wir:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>(b1 <span class="ot">&lt;-</span> beta_stud_1 <span class="sc">*</span> <span class="fu">sd</span>(dt<span class="sc">$</span>mpg) <span class="sc">/</span> <span class="fu">sd</span>(dt<span class="sc">$</span>hp))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.06822828</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Und setzen wir das in unsere Gleichung zur Bestimmung von <span class="math inline">\(\hat\beta_0\)</span> ein:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(b0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(dt<span class="sc">$</span>mpg) <span class="sc">-</span> b1 <span class="sc">*</span> <span class="fu">mean</span>(dt<span class="sc">$</span>hp))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 30.09886</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>so erhalten wir die Schätzwerte des ursprünglichen Problem.</p>
</section>
<section id="ein-anderer-weg-um-die-regressionskoeffizenten-zu-bestimmen" class="level3">
<h3 class="anchored" data-anchor-id="ein-anderer-weg-um-die-regressionskoeffizenten-zu-bestimmen">Ein anderer Weg um die Regressionskoeffizenten zu bestimmen…</h3>
<p>Gehen wir das Problem noch einmal neu an. Wir suchen <span class="math inline">\(\hat\beta=(\hat\beta_0, \hat\beta_1)\)</span> welches <span class="math inline">\(QS(\hat\beta) = QS(\hat\beta_0, \hat\beta_1) = \sum\limits_{i=1}^n \left(\hat\beta_0 + \hat\beta_1 \cdot x_i - y_i \right)^2\)</span> minimiert.</p>
<p>Statt es direkt, wie oben durch Null setzen der partiellen Ableitungen, zu bestimmen, wählen wir nun einen mathematisch-<em>numerischen</em> Ansatz und wollen <span class="math inline">\(\hat\beta \in \mathbf{R}^2\)</span> als <em>Optimierungsproblem</em> mit Hilfe des <em>Gradientenverfahrens</em> lösen.</p>
<p>Beim Gradientenverfahren wird versucht, ausgehend von einem Startwert <span class="math inline">\(\hat\beta^0 \in \mathbf{R}^2\)</span>, gemäß der Iterationsvorschrift</p>
<p><span class="math display">\[
\hat\beta^{k+1} = \hat\beta^{k} + \alpha^k \cdot d^k
\]</span></p>
<p>für alle <span class="math inline">\(k=0,1, ...\)</span> eine Näherungslösung für <span class="math inline">\(\hat\beta\)</span> zu finden. Dabei ist <span class="math inline">\(\alpha^k &gt; 0\)</span> eine <em>positive Schrittweite</em> und <span class="math inline">\(d^k\in\mathbf{R}^n\)</span> eine <em>Abstiegsrichtung</em>, welche wir in jedem Iterationsschritt <span class="math inline">\(k\)</span> so bestimmen, dass die Folge <span class="math inline">\(\hat\beta^k\)</span> zu einem stationären Punkt, unserer Näherungslösung, konvergiert.</p>
<p>Im einfachsten Fall, dem <strong>Verfahren des steilsten Abstieges</strong>, wird der Abstiegsvektor <span class="math inline">\(d^k\)</span> aus dem Gradienten <span class="math inline">\(\nabla QS\)</span> wie folgt bestimmt:</p>
<p><span class="math display">\[
d^k = -\nabla QS\left(\hat\beta^k\right)
\]</span></p>
<p>Wegen <span class="math display">\[
\frac{\partial}{\partial \hat\beta_0} \, QS = 2 \cdot n \cdot \left(  \hat\beta_0 + \hat\beta_1\cdot\bar{x} - \bar{y} \right)
\]</span></p>
<p>und</p>
<p><span class="math display">\[
\frac{\partial}{\partial \hat\beta_1} \, QS = 2 \cdot \left(\hat\beta_1 \cdot \sum\limits_{i=1}^n(x_i-\bar{x})^2 - \sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y}) \right)
\]</span></p>
<p>gilt:</p>
<p><span class="math display">\[
\begin{aligned}
\nabla QS(\hat\beta) &amp;= \nabla QS(\hat\beta_0, \hat\beta_1) \\
&amp;= 2 \cdot \begin{pmatrix}
n \cdot(\hat\beta_0 + \hat\beta_1\cdot\bar{x} - \bar{y})  \\
\hat\beta_1 \cdot \sum\limits_{i=1}^n(x_i-\bar{x})^2 - \sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})
\end{pmatrix}
\end{aligned}
\]</span></p>
<p>Wir wollen hier von Anfang an mit den studentisierten Werten arbeiten, weil diese numerisch viele Vorteile haben. Darum vereinfachen sich die beiden partiellen Ableitungen noch einmal zu:</p>
<p><span class="math display">\[
\frac{\partial}{\partial \hat\beta_0} \, QS = 2 \cdot v
\]</span></p>
<p>und</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial}{\partial \hat\beta_1} \, QS &amp;= 2 \cdot \left(\hat\beta_1 \cdot \sum\limits_{i=1}^n(x_i-\bar{x})^2 - \sum\limits_{i=1}^n (x_i-\bar{x}) \cdot (y_i-\bar{y})\right) \\
&amp;= 2 \cdot (n-1) \left(\hat\beta_1 \cdot s^2_{x} - s_{x,y}\right)
\end{aligned}
\]</span></p>
<p>Somit gilt:</p>
<p><span class="math display">\[
\begin{aligned}
\nabla QS(\hat\beta) &amp;= \nabla QS(\hat\beta_0, \hat\beta_1) \\
&amp;= 2 \cdot \begin{pmatrix}
n \cdot \hat\beta_0 \\
(n-1) \left(\hat\beta_1 \cdot s^2_{x} - s_{x,y}\right)
\end{pmatrix}
\end{aligned}
\]</span></p>
<p>Um die Varianz und die Kovarianz nicht jedesmal neu zu berechnen, speichern wir die Ergebnisse vorab. Ebenso, damit der Quellcode kürzer wird, speichern wir in <span class="math inline">\(x\)</span> und <span class="math inline">\(y\)</span> die studentisierten Werte von <span class="math inline">\(hp\)</span> und <span class="math inline">\(mpg\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vorbereitungen </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>var_x <span class="ot">&lt;-</span> <span class="fu">var</span>(<span class="sc">~</span> hp_stud, <span class="at">data =</span> dt)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>cov_xy <span class="ot">&lt;-</span> <span class="fu">cov</span>(mpg_stud <span class="sc">~</span> hp_stud, <span class="at">data =</span> dt)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dt<span class="sc">$</span>hp_stud)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> dt<span class="sc">$</span>hp_stud</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> dt<span class="sc">$</span>mpg_stud</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Nun erstellen wir die <span class="math inline">\(QS\)</span> und <span class="math inline">\(\nabla QS\)</span> Funktionen: Wir definieren diese Funktion wie folgt in <strong>R</strong>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>qs <span class="ot">&lt;-</span> <span class="cf">function</span>(b_0, b_1) {</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((b_1 <span class="sc">*</span> x <span class="sc">-</span> y)<span class="sc">**</span><span class="dv">2</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>nabla_qs <span class="ot">&lt;-</span> <span class="cf">function</span>(b_0, b_1) {</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="dv">2</span> <span class="sc">*</span> n <span class="sc">*</span> b_0,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span> <span class="sc">*</span> (n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> (b_1 <span class="sc">*</span> var_x <span class="sc">-</span> cov_xy)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Die Schrittweite <span class="math inline">\(alpha\)</span> bestimmen wir mit Hilfe der <em>Armijo-Bedingung</em> und der <em>Backtracking Liniensuche</em>: Diese formalisiert das Konzept “genügend” in der geforderten Verringerung des Funktionswertes. Die Bedingung <span class="math inline">\(f(x^k + \alpha d^k) &lt; f(x^k)\)</span> wird modifiziert zu <span class="math display">\[f(x^k + \alpha d^k) \leq f(x^k) + \sigma \alpha \left(\nabla f(x^k)\right)^T d^k,\]</span> mit <span class="math inline">\(\sigma\in (0,1)\)</span>. Die Armijo-Bedingung umgeht Konvergenzprobleme der einfachen Bedingung, indem sie fordert, dass die Verringerung zumindest proportional zur Schrittweite und zur Richtungsableitung <span class="math inline">\(\left(\nabla f(x^k)\right)^T d^k\)</span> ist, mit Hilfe der Proportionalitätskonstante <span class="math inline">\(\sigma\)</span>. In der Praxis werden oft sehr kleine Werte verwendet, z.B. <span class="math inline">\(\sigma=0.0001\)</span>.</p>
<p>Die <em>Backtracking-Liniensuche</em> verringert die Schrittweite wiederholt um den Faktor <span class="math inline">\(\rho\)</span> (<code>rho</code>) , bis die Armijo-Bedingung erfüllt ist. Sie terminiert garantiert nach einer endlichen Anzahl von Schritten. Weshalb wir sie hier einsetzen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>alpha_k <span class="ot">&lt;-</span> <span class="cf">function</span>(b_0, b_1, d_k, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">sigma =</span> <span class="fl">0.0001</span>, <span class="at">rho =</span> <span class="fl">0.5</span>) {</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  d_0 <span class="ot">&lt;-</span> d_k[<span class="dv">1</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  d_1 <span class="ot">&lt;-</span> d_k[<span class="dv">2</span>]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  nabla <span class="ot">&lt;-</span> <span class="fu">nabla_qs</span>(b_0, b_1)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  n_0 <span class="ot">&lt;-</span> nabla[<span class="dv">1</span>]</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  n_1 <span class="ot">&lt;-</span> nabla[<span class="dv">2</span>]</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  lhs <span class="ot">&lt;-</span> <span class="fu">qs</span>(b_0 <span class="sc">+</span> alpha<span class="sc">*</span>d_0, b_1 <span class="sc">+</span> alpha<span class="sc">*</span>d_1)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  rhs <span class="ot">&lt;-</span> <span class="fu">qs</span>(b_0, b_1) <span class="sc">+</span> sigma<span class="sc">*</span>alpha<span class="sc">*</span>(n_0<span class="sc">*</span>d_0 <span class="sc">+</span> n_1<span class="sc">*</span>d_1)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">while</span> (lhs <span class="sc">&gt;</span> rhs) {</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    alpha <span class="ot">&lt;-</span> rho <span class="sc">*</span> alpha</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    lhs <span class="ot">&lt;-</span> <span class="fu">qs</span>(b_0 <span class="sc">+</span> alpha<span class="sc">*</span>d_0, b_1 <span class="sc">+</span> alpha<span class="sc">*</span>d_1)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    rhs <span class="ot">&lt;-</span> <span class="fu">qs</span>(b_0, b_1) <span class="sc">+</span> sigma<span class="sc">*</span>alpha<span class="sc">*</span>(n_0<span class="sc">*</span>d_0 <span class="sc">+</span> n_1<span class="sc">*</span>d_1)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(alpha)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Ein paar Einstellungen vorab:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># maximale Anzahl an Iterationen</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>max_iter <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>iter <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Genauigkeit</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>eps <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">**-</span><span class="dv">6</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Startwerte</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>b_0 <span class="ot">&lt;-</span> <span class="dv">0</span> </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>b_1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span> </span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Für eine vorgegebene Genauigkeit <span class="math inline">\(eps=10^{-6}\)</span>, den Startwerten <span class="math inline">\(\hat\beta_0^0 = 0\)</span> und <span class="math inline">\(\hat\beta_1^0 = -1\)</span> können wir somit das Verfahren starten:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> (<span class="cn">TRUE</span>) {</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  iter <span class="ot">&lt;-</span> iter <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  d_k <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">nabla_qs</span>(b_0, b_1)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  ad_ <span class="ot">&lt;-</span> <span class="fu">alpha_k</span>(b_0, b_1, d_k) <span class="sc">*</span> d_k</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  x0 <span class="ot">&lt;-</span> b_0 <span class="sc">+</span> ad_[<span class="dv">1</span>]</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  x1 <span class="ot">&lt;-</span> b_1 <span class="sc">+</span> ad_[<span class="dv">2</span>]</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> ((<span class="fu">abs</span>(b_0 <span class="sc">-</span> x0) <span class="sc">&lt;</span> eps) <span class="sc">&amp;</span> (<span class="fu">abs</span>(b_1 <span class="sc">-</span> x1) <span class="sc">&lt;</span> eps) <span class="sc">|</span> (iter <span class="sc">&gt;</span> max_iter)) {</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">break</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  b_0 <span class="ot">&lt;-</span> x0</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  b_1 <span class="ot">&lt;-</span> x1</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Wir haben in <span class="math inline">\(203\)</span> Iterationsschritten das folgende Ergebnis für die Regressionskoeffizienten:</p>
<p><span class="math display">\[
\hat\beta_0^{stud} = 0 \qquad \hat\beta_1^{stud} = -0.7761689
\]</span></p>
<p>Betrachten wir die daraus erstellte Regressionsgerade:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Um die Regressionskoeffizienten für unser ursprüngliches Problem zu erhalten müssen wir wie folgt zurück rechnen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(b1 <span class="ot">&lt;-</span> b_1 <span class="sc">*</span> <span class="fu">sd</span>(dt<span class="sc">$</span>mpg) <span class="sc">/</span> <span class="fu">sd</span>(dt<span class="sc">$</span>hp))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.06822832</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>(b0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(dt<span class="sc">$</span>mpg) <span class="sc">-</span>  b1 <span class="sc">*</span> <span class="fu">mean</span>(dt<span class="sc">$</span>hp))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 30.09887</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Die Geradengleichung für das ursprüngliches Problem lautet somit:</p>
<p><span class="math display">\[
\begin{aligned}
  \hat{y} &amp;= \hat\beta_0 + \hat\beta_1 \cdot x \\
          &amp;\approx 30.0988668 -0.0682283 \cdot x \\
          &amp;\approx 30.099 -0.068 \cdot x
\end{aligned}
\]</span></p>
</section>
<section id="die-r-funktion-optim" class="level3">
<h3 class="anchored" data-anchor-id="die-r-funktion-optim">Die R Funktion <code>optim</code></h3>
<p>In <strong>R</strong> gibt es bessere Optimierungsmethoden, als die hier verwendete. Zum Beispiel können wir die Funktion <code>optim</code> verwenden. Die Funktion <code>optim</code> benötigt die zu optimierende <span class="math inline">\(f(x)\)</span> und ggf. die Gradientenfunktion <span class="math inline">\(gf(x)\)</span> sowie einen Startpunkt <span class="math inline">\(x^0\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qs</span>(beta[<span class="dv">1</span>], beta[<span class="dv">2</span>])</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>grf <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nabla_qs</span>(beta[<span class="dv">1</span>], beta[<span class="dv">2</span>])</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Der eigentliche Aufruf von optim:</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>ergb <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="fl">0.5</span>),f ,grf, <span class="at">method =</span> <span class="st">"CG"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Auslesen der Schätzer aus dem Ergebnis:</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>(optim_beta_0 <span class="ot">&lt;-</span> ergb<span class="sc">$</span>par[<span class="dv">1</span>])</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>(optim_beta_1 <span class="ot">&lt;-</span> ergb<span class="sc">$</span>par[<span class="dv">2</span>])</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.7761683</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Wir erhalten somit für das studentisierte Problem die Gerade:</p>
<p><span class="math display">\[
\begin{aligned}
  \hat{y}^{stud} &amp;= \hat\beta_0^{stud} + \hat\beta_1^{stud} \cdot x^{stud} \\
          &amp;\approx 0 -0.7761683 \cdot  x^{stud} \\
          &amp;\approx 0 -0.776 \cdot  x^{stud}
\end{aligned}
\]</span></p>
<p>Für das ursprüngliche Problem rechnen wir mittels</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>optim_b1 <span class="ot">&lt;-</span> optim_beta_1 <span class="sc">*</span> <span class="fu">sd</span>(dt<span class="sc">$</span>mpg) <span class="sc">/</span> <span class="fu">sd</span>(dt<span class="sc">$</span>hp)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>optim_b0 <span class="ot">&lt;-</span> <span class="fu">mean</span>(dt<span class="sc">$</span>mpg) <span class="sc">-</span>  optim_b1 <span class="sc">*</span> <span class="fu">mean</span>(dt<span class="sc">$</span>hp)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>um und erhalten:</p>
<p><span class="math display">\[
\begin{aligned}
  \hat{y} &amp;= \hat\beta_0 + \hat\beta_1 \cdot x \\
          &amp;\approx 30.0988601 -0.0682283 \cdot x \\
          &amp;\approx 30.099 -0.068 \cdot x
\end{aligned}
\]</span></p>
</section>
</section>
<section id="idee-summe-der-absoluten-abweichungen" class="level2">
<h2 class="anchored" data-anchor-id="idee-summe-der-absoluten-abweichungen">2. Idee: Summe der absoluten Abweichungen</h2>
<p>Wir ändern nun die Abweichungsmessfunktion von der <em>Q</em>uadrat-<em>S</em>umme hin zu den <strong>A</strong>bsolut-<em>S</em>ummen:</p>
<p><span class="math display">\[
AS = AS(\hat\beta) = AS(\hat\beta_0, \hat\beta_1) = \sum_{i=1}^n |\hat{y}_i - y_i|
\]</span></p>
<p>Auch hier wollen wir mit den studentisierten Daten arbeiten und stellen die Funktion der <em>A</em>bsolut-<em>S</em>ummen auf:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Absolute Abweichungssummen</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>as <span class="ot">&lt;-</span> <span class="cf">function</span>(b_0, b_1) {</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">sum</span>(<span class="fu">abs</span>(b_0 <span class="sc">+</span> b_1 <span class="sc">*</span> x <span class="sc">-</span> y)))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Danach konstruieren wir die zu optimierende Funktion <span class="math inline">\(f\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Zu optimierende Funktion</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(beta) {</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as</span>(beta[<span class="dv">1</span>], beta[<span class="dv">2</span>])</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Diesmal nutzen wir <code>optim</code> ohne eine Gradientenfunktion:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ergb <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="sc">-</span><span class="dv">1</span>), f)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Schätzer auslesen</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>(opti_as_beta_0 <span class="ot">&lt;-</span> ergb<span class="sc">$</span>par[<span class="dv">1</span>])</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.1304518</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>(opti_as_beta_1 <span class="ot">&lt;-</span> ergb<span class="sc">$</span>par[<span class="dv">2</span>])</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.6844911</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Schauen wir uns nun die so erhaltene Gerade im Vergleich mit der ‘normalen’ Regressionsgerade an:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-25-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>In grün und gestrichelt sehen wir die Gerade aus der <em>Idee der quadratischen Abweichungssummen</em>, in blau die aus der <em>Idee der absoluten Abweichungssummen</em>.</p>
<p>Für unser ursprüngliches Problem rechnen wir um:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Umrechnen in die ursprüngliche Fragestellung</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>(as_b1 <span class="ot">&lt;-</span> opti_as_beta_1 <span class="sc">*</span> <span class="fu">sd</span>(dt<span class="sc">$</span>mpg) <span class="sc">/</span> <span class="fu">sd</span>(dt<span class="sc">$</span>hp))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -0.06016948</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>(as_b0 <span class="ot">&lt;-</span> (<span class="fu">mean</span>(dt<span class="sc">$</span>mpg) <span class="sc">-</span> as_b1 <span class="sc">*</span> <span class="fu">mean</span>(dt<span class="sc">$</span>hp)) <span class="sc">+</span> opti_as_beta_0 <span class="sc">*</span> <span class="fu">sd</span>(dt<span class="sc">$</span>mpg))</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 28.13051</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Und die dazu gehörige Darstellung:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-27-1.webp" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Die Funktionsvorschrift für die (blaue) Regressionsgerade lautet:</p>
<p><span class="math display">\[
\begin{aligned}
  \hat{y} &amp;= \hat\beta_0 + \hat\beta_1 \cdot x \\
          &amp;\approx 28.1305094 -0.0601695 \cdot x \\
          &amp;\approx 28.131 -0.06 \cdot x
\end{aligned}
\]</span></p>
<p>Diese Methode nennt sich <strong>Median-Regression</strong> und ein ein Spezialfall der <strong>Quantilsregression</strong>, die sich u.a. mit dem R-Paket <a href="https://cran.r-project.org/web/packages/quantreg/index.html"><em>quantreg</em></a> unmittelbar umsetzen lässt:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quantreg)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ergmedianreg <span class="ot">&lt;-</span> <span class="fu">rq</span>(mpg <span class="sc">~</span> hp, <span class="at">data =</span> dt)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(ergmedianreg)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; (Intercept)          hp </span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 28.13050847 -0.06016949</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="idee-betrag-der-summe-der-abweichungen" class="level2">
<h2 class="anchored" data-anchor-id="idee-betrag-der-summe-der-abweichungen">1. Idee: Betrag der Summe der Abweichungen</h2>
<p>Wenn wir die Summe der Abweichungen <span class="math inline">\(\sum\limits_{i=1}^n \hat{e}_i\)</span> minimieren wollen, dann ist es sinnvoll den Betrag davon zu minimieren. Wir suchen also die Schätzer <span class="math inline">\(\hat\beta_0\)</span> und <span class="math inline">\(\hat\beta_1\)</span>, so dass der Ausdruck</p>
<p><span class="math display">\[
\left| \sum_{i=1}^n \hat{e}_i \right| = \left| \sum_{i=1}^n (\hat\beta_0 + \hat\beta_1 \cdot x_i - y_i) \right|
\]</span></p>
<p>minimal ist.</p>
<p>Wegen:</p>
<p><span class="math display">\[
\begin{aligned}
\sum_{i=1}^n (\hat\beta_0 + \hat\beta_1 \cdot x_i - y_i)
&amp;= \sum_{i=1}^n \hat\beta_0 + \sum_{i=1}^n \hat\beta_1 \cdot x_i - \sum_{i=1}^n y_i \\
&amp;= n \cdot \hat\beta_0 + \hat\beta_1 \cdot \sum_{i=1}^n x_i - \sum_{i=1}^n y_i \\
&amp;= n \cdot \hat\beta_0 + \hat\beta_1 \cdot n \cdot \bar{x} - n \cdot \bar{y} \\
&amp;= n \cdot \left( \hat\beta_0 + \hat\beta_1 \cdot \bar{x} - \bar{y} \right) \\
&amp;= n \cdot \left( \hat\beta_0 - \bar{y} + \hat\beta_1 \cdot \bar{x}  \right)
\end{aligned}
\]</span></p>
<p>können wir das absolute Minimum bei <span class="math inline">\(\hat\beta_0 - \bar{y} =0\)</span> und <span class="math inline">\(\hat\beta_1 \cdot \bar{x}=0\)</span> erreichen, was zur Lösung <span class="math inline">\(\hat\beta_0 =\bar{y}\)</span> und <span class="math inline">\(\hat\beta_1 = 0\)</span> führt. Dies ist unser <em>Nullmodel</em> in dem die <span class="math inline">\(x_i\)</span> keinen Einfluss auf die <span class="math inline">\(y_i\)</span> haben und wir daher pauschal die <span class="math inline">\(y_i\)</span> mit <span class="math inline">\(\hat{y}_i=\bar{y}\)</span>, also dem Mittelwert der <span class="math inline">\(y_i\)</span> abschätzen.</p>
</section>
<section id="zusammenfassung" class="level2">
<h2 class="anchored" data-anchor-id="zusammenfassung">Zusammenfassung</h2>
<p>Als Vergleich können wir uns die Quadratsumme <span class="math inline">\(QS\)</span> und Absolutsumme <span class="math inline">\(AS\)</span> der drei Modelle einmal ansehen:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quadratische Abweichungssummen</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>qs <span class="ot">&lt;-</span> <span class="cf">function</span>(b_0, b_1) {</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(((b_0 <span class="sc">+</span> b_1 <span class="sc">*</span> dt<span class="sc">$</span>hp) <span class="sc">-</span> dt<span class="sc">$</span>mpg )<span class="sc">**</span><span class="dv">2</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Absolute Abweichungssummen</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>as <span class="ot">&lt;-</span> <span class="cf">function</span>(b_0, b_1) {</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">abs</span>((b_0 <span class="sc">+</span> b_1 <span class="sc">*</span> dt<span class="sc">$</span>hp) <span class="sc">-</span> dt<span class="sc">$</span>mpg))</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quadratsummen:</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>quad_sum <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">qs</span>(b0, b1), <span class="fu">qs</span>(as_b0, as_b1), <span class="fu">qs</span>(mean_mpg, <span class="dv">0</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Absolutsummen:</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>abs_sum <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">as</span>(b0, b1), <span class="fu">as</span>(as_b0, as_b1), <span class="fu">as</span>(mean_mpg, <span class="dv">0</span>))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">sums =</span> <span class="fu">c</span>(quad_sum, abs_sum),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">sum_type =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"quad"</span>, <span class="st">"abs"</span>), <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">methode =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Idee 3"</span>, <span class="st">"Idee 2"</span>, <span class="st">"Idee 1"</span>), <span class="dv">2</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_wider</span>(tab, <span class="at">names_from=</span>sum_type, <span class="at">values_from=</span>sums, <span class="at">names_sort=</span>T)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 3 × 3</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   methode   abs  quad</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 Idee 3   93.0  448.</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 Idee 2   87.3  477.</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 Idee 1  151.  1126.</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="reproduzierbarkeitsinformationen" class="level2">
<h2 class="anchored" data-anchor-id="reproduzierbarkeitsinformationen">Reproduzierbarkeitsinformationen</h2>
<div class="cell" data-layout-align="center">
<pre><code>#&gt; R version 4.5.1 (2025-06-13)
#&gt; Platform: aarch64-apple-darwin20
#&gt; Running under: macOS Sequoia 15.5
#&gt; 
#&gt; Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8
#&gt; 
#&gt; Package version:
#&gt;   mosaic_1.9.1 quantreg_6.1 tidyr_1.3.1  xfun_0.52</code></pre>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Fußnoten</h2>

<ol>
<li id="fn1"><p>Das “Cookbook” zur Datentabelle können Sie mit Hilfe von <code>help("mtcars")</code> aufrufen!<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/www\.sefiroth\.de");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>