---
title: "Einfach ein paar gute Seite zum Thema RaspberryPi Pico"
author: "Norman Markgraf"
lang: de-DE
date: "2026-02-20"
date-modified: last-modified
word-count: true
reading-time: true
categories: 
  - RasperryPi
  - RaspberryPi Pico
---

# Einfach ein paar gute Seite zum Thema RaspberryPi Pico

Ich habe auf den Seiten von LHlab Wiki [hier](https://lhlab.wiki/wiki/Kategorie:RaspberryPiPico) ein paar Seiten zum Thema RaspberryPi Pico gefunden die ich für recht interessant halte.

Für die ersten Schritte mit dem RaspberryPi Pico könnte die Seite [https://www.elektronik-kompendium.de/sites/raspberry-pi/2612191.htm](https://www.elektronik-kompendium.de/sites/raspberry-pi/2612191.htm) sehr hilfreich sein.

Informationen zu den Anschlüssen des RaspberryPi Pico finden wir auf der Seite [https://www.elektronik-kompendium.de/sites/raspberry-pi/2611031.htm](https://www.elektronik-kompendium.de/sites/raspberry-pi/2611031.htm).

Eine guter Belegungsplan der GPIO Pins des RaspberryPi Pico findet sich auf der Seite [https://www.elektronik-kompendium.de/sites/raspberry-pi/2611051.htm](https://www.elektronik-kompendium.de/sites/raspberry-pi/2611051.htm).

Informationen zum Schlafmodues des RaspberryPi Pico findet sich auf der Seite [https://www.elektronik-kompendium.de/sites/raspberry-pi/2802131.htm](https://www.elektronik-kompendium.de/sites/raspberry-pi/2802131.htm).




##

Unter [https://raw.githubusercontent.com/alaub81/rpi_pico_scripts/main/config_sample.py](https://raw.githubusercontent.com/alaub81/rpi_pico_scripts/main/config_sample.py) gibt es eine Beispielkonfiguration für die Nutzung von MicroPython auf dem RaspberryPi Pico. Das könnte für Einsteiger sehr hilfreich sein, um schnell loszulegen und die ersten Schritte mit dem Pico zu machen.

[https://raw.githubusercontent.com/alaub81/rpi_pico_scripts/main/wificonnection.py](https://raw.githubusercontent.com/alaub81/rpi_pico_scripts/main/wificonnection.py)



## Raspberry Pi OS download

[https://www.raspberrypi.com/software/operating-systems/](https://www.raspberrypi.com/software/operating-systems/)

