---
title: "Lineare und logistische Regression in Python"
author: "Norman Markgraf"
lang: de-DE
date: "2026-05-30"
date-modified: last-modified
word-count: true
reading-time: true
#draft: true
categories: 
  - Statistik
  - Lineare Regression
  - Logistische Regression
  - Python
---

## Vorbereitung

```{python}
#| echo: false
from IPython.display import Markdown;
```

Wir wollen hier mit den Daten aus der Datentabelle Schwertlinien (engl. _iris flower data set_) von Anderson bzw. Fisher. ^[vgl.: <https://de.wikipedia.org/wiki/Schwertlilien-Datensatz>]

Die Datentabelle enthält 150 Messungen von fünf Attributen: 

- Länge des Kelchblatts (sepal length in cm), 
- Breite des Kelchblatts (sepal width in cm), 
- Länge des Kronblatts (petal length in cm), 
- Breite des Kronblatts (petal width in cm) sowie 
- Art (_Spezies_) (Borsten-Schwertlilie (_Iris setosa_) = 0, Verschiedenfarbige  oder Schillernde  Schwertlilie (_Iris versicolor_) = 1 und  Virginische Schwertlilie (_Iris virginica_) = 2)

Finden kann mensch diese im Paket `sklearn.datasets` und laden mit dem Befehl `load_iris()`:

```{python}
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

# Aus den Daten erzeugen wir einen Datenrahmen
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target
```

Ein Blick auf `X`:

```{python}
X.head()
```

Ein Blick auf `y`:

```{python}
y
```


## (Einfache) Lineare Regression

Am Anfang steht eine *(einfache) linearen Regression*.
Dabei erstellen wir ein Modell, bei dem wir die Länge des Kronblatts (_petal length_) auf Grundlage der Länge des Kelchblatts (_sepal length_) modellieren wollen. Also eine unabhängige Variable (_UV_, _Prädiktoren_, engl.: _predictors_) und eine (abhängige) Variable (_AV_, _Zielvariable_ engl.: _target_).

```{python}
# Zielvariable y_reg: Petal Length
y_reg = X["petal length (cm)"]
# Modellierungsvariable X_reg: Sepal Legth
X_reg = X.drop(columns=["petal length (cm)", "sepal width (cm)", "petal width (cm)"])
```

Wir teilen nun unsere Daten in Test- und Trainingsdaten auf. Dabei sollen $0.2=20\,\%$ der Daten zu Testdaten werden und $1-0.2=0.8=80\,\%$ zu Trainingsdaten.

Die Auswahl erfolgt zufällig. Wobei wir hier einen mit `random_state=2009` dafür sorgen, dass dieser Zufall reproduzierbar ist.

```{python}
from sklearn.model_selection import train_test_split

# Aufteilen in Test- und Trainingsdaten
X_train, X_test, y_train, y_test = train_test_split(X_reg, y_reg, test_size=0.2, random_state=2009)
```

Nun erstellen wir das lineare Regressionmodell und trainieren dieses mit den Daten `X_train` und `y_train`

```{python}
from sklearn.linear_model import LinearRegression

# Modell
linreg = LinearRegression()
linreg.fit(X_train, y_train)
```

Um das Modell zu prüfen lassen wir es nun aus unseren Testdaten (`X_test`) die Zieldaten (`y_pred`) modellieren:

```{python}
# Vorhersage
y_pred = linreg.predict(X_test)
```

Da wir mit `y_test` die tatsächlichen Daten kennen, können wir das nun mit unserem vom Modell modellierten Werten vergleichen und so unsere Modell bewerten.

Wir nutzen dazu das die mittlere quadratische Abweichung (engl. _mean squared error_, kurz _MSE_), der mittleren absoluten Abweichung (engl. _mean_absolute_error_, kurz _MAE_) und das Bestimmtheitsmaß $R^2$.

```{python}
from sklearn.metrics import mean_squared_error, mean_absolute_error

print("MSE:", mean_squared_error(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R^2:", linreg.score(X_reg, y_reg))
```

Wir können die Regressionsgerade mit Hilfe der Koeffizienten und der Ordinate (engl.: _Intercept_) bestimmen:

```{python}
print("Koeffizienten:", linreg.coef_[0])
print("Intercept:", linreg.intercept_)
```


```{python}
# Steigung a
a = round(linreg.coef_[0].item(), 4)
# Ordinatenabschnitt b
b = round(linreg.intercept_.item(), 4)
# Für eine bessere Ausgabe:
pm = Markdown("+") if b >= 0 else Markdown("-")
absb = abs(b)
```

Daraus ergibt sich für die Regressionsgerade die Darstellung:

$$
  \hat{y} = \hat{f}(x) \approx `{python} a` \cdot x `{python} pm`  `{python} absb`
$$

Schauen wir uns das Streudiagramm unserer Test- und Trainingsdaten mit der Regressionsgeraden an:

```{python}
#| warning: false

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(8, 5))

# Streudiagramm der Trainings- und Testdaten
plt.scatter(X_train, y_train, color="blue", label="Trainingswerte")
plt.scatter(X_test, y_test, color="green", label="Testwerte")

# Regressionsgerade 
xp = np.linspace(4, 8, 200)  # 200 Messpunkte im Intervall [4; 8]
yp = a * xp + b  # y= a*x + b -- Werte auf unserer Regressionsgeraden
pm = "+" if b >= 0 else "-"
plt.plot(xp, yp, label=r'$\hat{y}$'+f'= {a}x {pm} {absb}', color='red')

plt.xlabel("Länge des Kelchblatts (cm)")
plt.ylabel("Länge des Kronblatts (cm)")
plt.title("Lineare Regression auf den Liliendaten")
plt.legend()
plt.grid(True)
plt.show()
```


## (Multiple) Lineare Regression 

Wir wollen nun bei der Modellierung auf alle drei anderen numerischen Variablen zurückgreifen.
Das führt zu einer *multiplen linearen Regression*.


```{python}
# Zielvariable: Petal Length
y_reg = X["petal length (cm)"]

# Modellierungsvariablen: Sepal Width, Petal Length und Petal Width
X_reg = X.drop(columns=["petal length (cm)"])

# Aufteilen in Test- und Trainingsdaten
X_train, X_test, y_train, y_test = train_test_split(X_reg, y_reg, test_size=0.20, random_state=2009)

# Modell
linreg = LinearRegression()
linreg.fit(X_train, y_train)

# Vorhersage
y_pred = linreg.predict(X_test)
```

Wir schauen uns die Gütekriterien _mittlere quadratischer Fehler_ (*MSE*), _mittlere absoluter Fehler_ (*MAE*) und das Bestimmtheitsmaß ($R^2$) an:

```{python}
print("MSE:", mean_squared_error(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R^2:", linreg.score(X_reg, y_reg))
```

Die Regressionsgerade wird durch die Koeffizienten und den Ordinatenabschnitt (_Intercept_) bestimmt:

```{python}
print("Koeffizienten:", linreg.coef_)
print("Intercept:", linreg.intercept_)
```

Wir erhalten somit die folgende Regressionsfunktion:

```{python}
#| echo: false
from IPython.display import Markdown;
a1 = round(linreg.coef_[0].item(), 4)
a2 = round(linreg.coef_[1].item(), 4)
a3 = round(linreg.coef_[2].item(), 4)
b = round(linreg.intercept_.item(), 4)
pm1 = Markdown("+") if a1 >= 0 else Markdown("-")
pm2 = Markdown("+") if a2 >= 0 else Markdown("-")
pm3 = Markdown("+") if a3 >= 0 else Markdown("-")
pmb = Markdown("+") if b >= 0 else Markdown("-")
```

$$
  \hat{y} = \hat{f}(x_1, x_2, x_3) 
          = `{python} a1` \cdot x_1 `{python} pm2` 
            `{python} abs(a2)` \cdot x_2 `{python} pm3` 
            `{python} abs(a3)` \cdot x_3 `{python} pmb` `{python} abs(b)`  
$$


## Einfache Logistische Regression 


Unsere Liliendaten bestehen aus den Längen und Breiten der Kelch- bzw. Korbblättern von drei Lilienarten. 

0 : Iris setosa (_Borsten-Schwertlilie_)

1 : Iris versicolor (_Verschiedenfarbige oder Schillernde Schwertlilie_)

2 : Iris virginica (_Virginische Schwertlilie_)

Wir schauen uns zunächst nur die _Iris setosa_ an, dafür setzen wir 'y' immer dann auf 1, wenn eine solche Lilienart vorliegt, sonst auf 0:

```{python}
y_logreg = np.where( y == 0, 1, 0)  # y == 0 für Iris setosa
y_logreg
X_logreg = X.drop(columns=["petal length (cm)", "sepal width (cm)", "petal width (cm)"])
X_logreg
```

Betrachten wir nun mit Hilfe eines Boxplots, wo unsere Werte für _Iris setose_ bzw _Nicht Iris setosa_ im Bezug auf die Länge des Kelchblatts (_sepal length_) liegen:

```{python}
plt.figure(figsize=(8, 5))
plt.suptitle("Boxplot Länge Kelchblatts Iris setosa bzw. andere")
setosa = X_logreg[y_logreg == 1]
notsetosa = X_logreg[y_logreg == 0]

plt.subplot(1,2,1)
plt.ylim(3, 8)
setosa.boxplot()
plt.title("Iris setosa")

plt.subplot(1, 2, 2)
plt.ylim(3, 8)
notsetosa.boxplot()
plt.title("Nicht Iris setosa")

plt.show()
```


Wenn wir eine lineare Regression auf diesen Daten durchführen würden, so sähe das wie folgt aus:

```{python}
# Aufteilen in Test- und Trainingsdaten
X_train, X_test, y_train, y_test = train_test_split(X_logreg, y_logreg, test_size=0.2, random_state=2009)
```

Wir erzeugen nun das Modell:

```{python}
linmod_linreg = LinearRegression()
linmod_linreg.fit(X_train, y_train)
```

Schauen wir uns nun die Koeffizienten und den Ordinatenabschnitt an:

```{python}
print("Koeffizienten:", linmod_linreg.coef_[0])
print("Intercept:", linmod_linreg.intercept_)
```

```{python}
a = round(linmod_linreg.coef_[0].item(), 4)
b = round(linmod_linreg.intercept_.item(), 4)
pm = Markdown("+") if b >= 0 else Markdown("-")
absb = abs(b)
```

Das dazugehörige Streudiagramm inkl. Regressionsgerade:

```{python}
#| warning: false
plt.figure(figsize=(8, 5))

# Streudiagramm der Trainingsdaten
plt.scatter(X_train, y_train, color="blue", label="Trainingswerte")
plt.scatter(X_test, y_test, color="green", label="Testwerte")

# Regressionsgerade
xp = np.linspace(4,8,200)
yp = a * xp + b
pm = "+" if b >= 0 else "-"
plt.plot(xp, yp, label=rf'f(x)= {a}x {pm} {absb}', color='red')

plt.xlabel("Länge des Kelchblatts (cm)")
plt.ylabel("")
plt.title("Lineare Regression auf den Liliendaten")
plt.legend()
plt.grid(True)
plt.show()
```

Statt des linearen Ansatzes, wollen wir eine Wahrscheinlichkeit modellieren ob eine entsprechende Länge des Kelchblattes für oder gegen eine Borsten-Schwertlilie (_Iris setosa_) spricht.

```{python}
from sklearn.linear_model import LogisticRegression

# Modell
logreg = LogisticRegression(max_iter=200)
logreg.fit(X_train, y_train)
```

```{python}
a = round(logreg.coef_.item(), 4)
b = round(logreg.intercept_.item(), 4)
absb = abs(b)
```

```{python}
#| warning: false
plt.figure(figsize=(8, 5))

# Streudiagramm der Trainingsdaten
plt.scatter(X_train, y_train, color="blue", label="Trainingswerte")
plt.scatter(X_test, y_test, color="green", label="Testwerte")

# Regressionsfunktion ermitteln
import pandas as pd

xp = pd.DataFrame(
    np.linspace(4, 8, 200),
    columns=["sepal length (cm)"]
)
yp = logreg.predict_proba(xp)[:,1] 
pm = "+" if b >= 0 else "-"
plt.plot(xp, yp, label=r'$P(y = 1) = $'+f'expit({a}x {pm} {absb})', color='red')

plt.xlabel("Länge des Kelchblatts (cm)")
plt.ylabel("Wahrscheinlichkeit für Iris setosa")
plt.title("Logistische Regression auf den Liliendaten")
plt.legend()
plt.grid(True)
plt.show()
```


Dabei bezeichnet $expit(x)$ die _logistische Funktion_ (auch _sigmonide Funktion_ oder kurt _Sigmonide_ genannt) und ist die Umkehrfunktion der $logit$-Funktion.


Wir können an der Grafik schon erkennen, das unser Ansatz so nicht unbedingt optimal ist. Schauen wir uns aber dennoch die Gütemaße an:

Die orginalen Testwerte $y_test$:
```{python}
y_test
```

Die durch die Regression geschätzten Werte $y_pred$:
```{python}
y_pred = logreg.predict(X_test)
y_pred
```

```{python}
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-Score:", f1_score(y_test, y_pred))
```

Etwas detailierter können wir uns das mit dem folgenden Befehl komplett ansehen:

```{python}
print(classification_report(y_test, y_pred, target_names=["Nicht I. setosa", "Iris setosa"], digits=3))
```

Wagen wir kurz einen Blick auf alle Daten (Test- wie Trainingsdaten):

```{python}
print(classification_report(y_logreg, logreg.predict(X_logreg), target_names=["Nicht I. setosa", "Iris setosa"], digits=3))
```


## Multinomiale Logistische Regression


Wir teilen unsere Daten wieder in Test- und Trainingsdaten auf:

```{python}
# Klassifikationsdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2009)
```

Erstellen wir nun ein logistisches Regressionsmodell und trainieren dieses.

```{python}
# Modell
logreg = LogisticRegression(max_iter=200)
logreg.fit(X_train, y_train)
```

Erzeugen wir nun aus unserem Modell eine Vorhersage für die Testdaten:

```{python}
# Vorhersage
y_pred = logreg.predict(X_test)
```

Schauen wir uns für die Testdaten einmal die echten und vorhergesagten Werte an:
```{python}
# Vergleich der Testdaten ...
y_test
```
```{python}
# ... mit den durch das Modellgeschätzen Daten
y_pred
```

Berechnen wir die üblichen Gütemaße:

```{python}
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall:", recall_score(y_test, y_pred, average='weighted'))
print("F1-Score:", f1_score(y_test, y_pred, average='weighted'))
```

Etwas detailierter können wir uns das mit dem folgenden Befehl komplett ansehen:

```{python}
print(classification_report(y_test, y_pred, target_names=iris.target_names, digits=3))
```

Wagen wir kurz einen Blick auf alle Daten (Test- wie Trainingsdaten):

```{python}
print(classification_report(y, logreg.predict(X), target_names=iris.target_names, digits=3))
```
