---
title: "Quarto-Dokumente mit WebP anstatt PNG Bilddateien erstellen"
author: "Norman Markgraf"
lang: de-DE
date: "2025-12-03"
date-modified: last-modified
word-count: true
reading-time: true
categories: 
  - Quarto
---

# WebP statt PNG?

Ich bin über die Quarto-Extension von Klaus Brunner mit dem Namen [Convert PNG to WebP (Quarto Extension)](https://github.com/klausbrunner/convert-to-webp) gestolpert und nutze diesen nun regelmässig.

Dafür habe ich auf meinem Mac via HomeBrew die Application "webp" installiert.

```bash
> brew install webp
```

Dadurch habe ich das Programm `cwebp` installiert. Es dient zum umwandeln von PNG in webp Dateien.
Zum Testen nutze ich den Befehl:
```bash
> cwebp -version
```

Aktuell bekomme ich damit die Ausgabe:
```
1.6.0
libsharpyuv: 0.4.2
```

Das Programm ersetzt die erzeugten Bild-Ausgaben, welche normalerweise im PNG-Format erzeugt werden, durch Neue im WebP-Format.

Die KI sagt:

> WebP ist ein modernes Bildformat von Google, das eine effizientere Komprimierung als herkömmliche Formate wie JPEG und PNG ermöglicht, um Bilder im Web kleiner zu machen und Ladezeiten zu beschleunigen. Es unterstützt sowohl verlustfreie als auch verlustbehaftete Komprimierung sowie Transparenz und Animationen, ähnlich wie PNG und GIF. WebP wird von den meisten modernen Browsern unterstützt, aber für ältere Browser ist es ratsam, eine alternative Bildversion bereitzustellen


## Installation im Quarto-Projekt

Um sofort bei der Erstellung von Dokumenten, wie zum Beispiel diese Blog-Einträge, mit Quarto webp zu nutzen, installiert mensch einfach im Quarto-Projekt mittels:
```bas
> quarto add klausbrunner/convert-to-webp
```

Danach in der Datei `_quarto.yml` noch die folgenden Zeilen hinzufügen:

```yml
filters:
  - convert-to-webp

webp-delete-originals: false
webp-disable: false
```

Jetzt wird nach jedem 'rendern' eines Dokuments die erzeugten PNG-Dateien in WebP-Dateien übersetzt und im HTML-Code entsprechend ersetzt.
